# Generated by Django 5.2.3 on 2025-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('SED', 'Sedan'), ('HAT', 'Hatchback'), ('COP', 'Couple'), ('CON', 'Convertible'), ('LIM', 'Limousine'), ('VAN', 'Van'), ('MVN', 'Minivan'), ('TRU', 'Truck'), ('SWG', 'Station wagon'), ('PIC', 'Pickup'), ('OFR', 'Off-road car'), ('CRS', 'Crossover'), ('SPR', 'Sports car')], default='SED', max_length=3)),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('TOY', 'Toyota'), ('PGT', 'Peugeot'), ('MTS', 'Mitsubishi'), ('LXS', 'Lexus'), ('FRD', 'Ford'), ('SKD', 'Skoda'), ('LAD', 'LADA'), ('MER', 'Mercedes'), ('HYU', 'Hyundai'), ('MZD', 'Mazda'), ('AUD', 'Audi'), ('CTN', 'Citroen'), ('RNL', 'Renault'), ('VKS', 'Volkswagen')], default='BMW', max_length=3)),
                ('release_year', models.PositiveIntegerField()),
                ('colour', models.CharField(max_length=55)),
                ('mileage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('release_year__gte', 1850)), name='release_year_gte_1850')],
            },
        ),
    ]
