# Generated by Django 5.2.4 on 2025-07-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealershipcars',
            old_name='purchase_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='dealershipcars',
            old_name='purchase_price_currency',
            new_name='price_currency',
        ),
    ]
