name: Django Auto

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build:
    env:
      DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: 'localhost 127.0.0.1 [::1]'
      DATABASE_ENGINE: postgresql
      DATABASE_NAME: github_actions
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: '127.0.0.1'
      DATABASE_PORT: 5432
      REDIS_HOST: '127.0.0.1'
      REDIS_PORT: 6379
      python_version: '3.13'
      
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install --deploy --dev
    - name: Run migrations
      run: pipenv run python manage.py migrate
    - name: Run Tests
      run: pipenv run pytest
